# Generated by Django 6.0.7 on 2026-08-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='images/dog.webp', upload_to='profile_images'),
        ),
    ]
